name: build and push docker
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    if: (needs.check.outputs.pocketbase != needs.check.outputs.package) || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from needs or input
        id: version
        run: echo "value=${{ github.event.inputs.version || needs.check.outputs.pocketbase }}" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/my-invoice
          tags: |
            type=semver,pattern={{version}},value=${{ steps.version.outputs.value }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.version.outputs.value }}
            type=semver,pattern={{major}},value=${{ steps.version.outputs.value }}

      - name: Build and push
        permissions:
          contents: read
          packages: write
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: false
          build-args: VERSION=${{ steps.version.outputs.value }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
